#ifndef HCI_CONSTS_H
#define HCI_CONSTS_H

#include "bt.h"

// This is incomplete. If you use any commands/events not included here,
// please help us add them!

// Event codes
enum hci_event {
    EVENT_INQUIRY_COMPLETE                                  = 0x01,
    EVENT_INQUIRY_RESULT                                    = 0x02,
    EVENT_CONNECTION_COMPLETE                               = 0x03,
    EVENT_CONNECTION_REQUEST                                = 0x04,
    EVENT_DISCONNECTION_COMPLETE                            = 0x05,
    EVENT_AUTHENTICATION_COMPLETE                           = 0x06,
    EVENT_REMOTE_NAME_REQUEST_COMPLETE                      = 0x07,
    EVENT_ENCRYPTION_CHANGE                                 = 0x08,
    EVENT_CHANGE_CONNECTION_LINK_KEY_COMPLETE               = 0x09,
    EVENT_MASTER_LINK_KEY_COMPLETE                          = 0x0A,
    EVENT_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE           = 0x0B,
    EVENT_READ_REMOTE_VERSION_INFORMATION_COMPLETE          = 0x0C,
    EVENT_QOS_SETUP_COMPLETE                                = 0x0D,
    EVENT_COMMAND_COMPLETE                                  = 0x0E,
    EVENT_COMMAND_STATUS                                    = 0x0F,
    EVENT_HARDWARE_ERROR                                    = 0x10,
    EVENT_FLUSH_OCCURRED                                    = 0x11,
    EVENT_ROLE_CHANGE                                       = 0x12,
    EVENT_NUMBER_OF_COMPLETED_PACKETS                       = 0x13,
    EVENT_MODE_CHANGE                                       = 0x14,
    EVENT_RETURN_LINK_KEYS                                  = 0x15,
    EVENT_PIN_CODE_REQUEST                                  = 0x16,
    EVENT_LINK_KEY_REQUEST                                  = 0x17,
    EVENT_LINK_KEY_NOTIFICATION                             = 0x18,
    EVENT_LOOPBACK_COMMAND                                  = 0x19,
    EVENT_DATA_BUFFER_OVERFLOW                              = 0x1A,
    EVENT_MAX_SLOTS_CHANGE                                  = 0x1B,
    EVENT_READ_CLOCK_OFFSET_COMPLETE                        = 0x1C,
    EVENT_CONNECTION_PACKET_TYPE_CHANGED                    = 0x1D,
    EVENT_QOS_VIOLATION                                     = 0x1E,
    EVENT_PAGE_SCAN_REPETITION_MODE_CHANGE                  = 0x20,
    EVENT_FLOW_SPECIFICATION_COMPLETE                       = 0x21,
    EVENT_INQUIRY_RESULT_WITH_RSSI                          = 0x22,
    EVENT_READ_REMOTE_EXTENDED_FEATURES_COMPLETE            = 0x23,
    EVENT_SYNCHRONOUS_CONNECTION_COMPLETE                   = 0x2C,
    EVENT_SYNCHRONOUS_CONNECTION_CHANGED                    = 0x2D,
    EVENT_SNIFF_SUBRATING                                   = 0x2E,
    EVENT_EXTENDED_INQUIRY_RESULT                           = 0x2F,
    EVENT_ENCRYPTION_KEY_REFRESH_COMPLETE                   = 0x30,
    EVENT_IO_CAPABILITY_REQUEST                             = 0x31,
    EVENT_IO_CAPABILITY_RESPONSE                            = 0x32,
    EVENT_USER_CONFIRMATION_REQUEST                         = 0x33,
    EVENT_USER_PASSKEY_REQUEST                              = 0x34,
    EVENT_REMOTE_OOB_DATA_REQUEST                           = 0x35,
    EVENT_SIMPLE_PAIRING_COMPLETE                           = 0x36,
    EVENT_LINK_SUPERVISION_TIMEOUT_CHANGED                  = 0x38,
    EVENT_ENHANCED_FLUSH_COMPLETE                           = 0x39,
    EVENT_USER_PASSKEY_NOTIFICATION                         = 0x3B,
    EVENT_KEYPRESS_NOTIFICATION                             = 0x3C,
    EVENT_REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION       = 0x3D,
    EVENT_LE_META_EVENT                                     = 0x3E,
    EVENT_PHYSICAL_LINK_COMPLETE                            = 0x40,
    EVENT_CHANNEL_SELECTED                                  = 0x41,
    EVENT_DISCONNECTION_PHYSICAL_LINK_COMPLETE              = 0x42,
    EVENT_PHYSICAL_LINK_LOSS_EARLY_WARNING                  = 0x43,
    EVENT_PHYSICAL_LINK_RECOVERY                            = 0x44,
    EVENT_LOGICAL_LINK_COMPLETE                             = 0x45,
    EVENT_DISCONNECTION_LOGICAL_LINK_COMPLETE               = 0x46,
    EVENT_FLOW_SPEC_MODIFY_COMPLETE                         = 0x47,
    EVENT_NUMBER_OF_COMPLETED_DATA_BLOCKS                   = 0x48,
    EVENT_AMP_START_TEST                                    = 0x49,
    EVENT_AMP_TEST_END                                      = 0x4A,
    EVENT_AMP_RECEIVER_REPORT                               = 0x4B,
    EVENT_SHORT_RANGE_MODE_CHANGE_COMPLETE                  = 0x4C,
    EVENT_AMP_STATUS_CHANGE                                 = 0x4D,
    EVENT_TRIGGERED_CLOCK_CAPTURE                           = 0x4E,
    EVENT_SYNCHRONIZATION_TRAIN_COMPLETE                    = 0x4F,
    EVENT_SYNCHRONIZATION_TRAIN_RECEIVED                    = 0x50,
    EVENT_CONNECTIONLESS_SLAVE_BROADCAST_RECEIVE            = 0x51,
    EVENT_CONNECTIONLESS_SLAVE_BROADCAST_TIMEOUT            = 0x52,
    EVENT_TRUNCATED_PAGE_COMPLETE                           = 0x53,
    EVENT_SLAVE_PAGE_RESPONSE_TIMEOUT                       = 0x54,
    EVENT_CONNECTIONLES_SLAVE_BROADCAST_CHANNEL_MAP_CHANGE  = 0x55,
    EVENT_INQUIRY_RESPONSE_NOTIFICATION                     = 0x56,
    EVENT_AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED             = 0x57,
    EVENT_VENDOR_SPECIFIC_EVENT                             = 0xFF,
};


enum hci_ogf {
    LINK_CONTROL_OGF                = 0x01,
    LINK_POLICY_OGF                 = 0x02,
    CONTROLLER_BASEBAND_OGF         = 0x03,
    INFORMATIONAL_PARAMETERS_OGF    = 0x04,
    STATUS_PARAMETERS_OGF           = 0x05,
    TESTING_OGF                     = 0x06,
    LOW_ENERGY_OGF                  = 0x08,
    VENDOR_SPECIFIC_OGF             = 0x3F,
};

enum hci_opcode {
    CMD_INQUIRY                         = OPCODE(LINK_CONTROL_OGF, 0x01),
    CMD_CREATE_CONNECTION               = OPCODE(LINK_CONTROL_OGF, 0x05),
    CMD_DISCONNECT                      = OPCODE(LINK_CONTROL_OGF, 0x06),
    CMD_ACCEPT_CONNECTION_REQUEST       = OPCODE(LINK_CONTROL_OGF, 0x09),

    CMD_WRITE_DEFAULT_LINK_POLICY_SETTINGS  = OPCODE(LINK_POLICY_OGF, 0x01),

    CMD_SET_EVENT_MASK                  = OPCODE(CONTROLLER_BASEBAND_OGF, 0x01),
    CMD_RESET                           = OPCODE(CONTROLLER_BASEBAND_OGF, 0x03),
    CMD_DELETE_STORED_LINK_KEY          = OPCODE(CONTROLLER_BASEBAND_OGF, 0x12),
    CMD_WRITE_LOCAL_NAME                = OPCODE(CONTROLLER_BASEBAND_OGF, 0x13),
    CMD_READ_LOCAL_NAME                 = OPCODE(CONTROLLER_BASEBAND_OGF, 0x14),
    CMD_WRITE_CONNECTION_ACCEPT_TIMEOUT = OPCODE(CONTROLLER_BASEBAND_OGF, 0x16),
    CMD_READ_SCAN_ENABLE                = OPCODE(CONTROLLER_BASEBAND_OGF, 0x19),
    CMD_WRITE_SCAN_ENABLE               = OPCODE(CONTROLLER_BASEBAND_OGF, 0x1A),
    CMD_READ_CLASS_OF_DEVICE            = OPCODE(CONTROLLER_BASEBAND_OGF, 0x23),
    CMD_WRITE_INQUIRY_MODE              = OPCODE(CONTROLLER_BASEBAND_OGF, 0x45),
    CMD_WRITE_EXTENDED_INQUIRY_RESPONSE = OPCODE(CONTROLLER_BASEBAND_OGF, 0x52),
    CMD_WRITE_SIMPLE_PAIRING_MODE       = OPCODE(CONTROLLER_BASEBAND_OGF, 0x56),

    CMD_READ_LOCAL_VERSION_INFORMATION  = OPCODE(INFORMATIONAL_PARAMETERS_OGF, 0x01),
    CMD_READ_BUFFER_SIZE                = OPCODE(INFORMATIONAL_PARAMETERS_OGF, 0x05),
    CMD_READ_BD_ADDR                    = OPCODE(INFORMATIONAL_PARAMETERS_OGF, 0x09),

    CMD_LE_SET_EVENT_MASK                       = OPCODE(LOW_ENERGY_OGF, 0x01),
    CMD_LE_SET_ADVERTISING_PARAMETERS           = OPCODE(LOW_ENERGY_OGF, 0x06),
    CMD_LE_READ_ADVERTISING_CHANNEL_TX_POWER    = OPCODE(LOW_ENERGY_OGF, 0x07),
    CMD_LE_SET_ADVERTISING_DATA                 = OPCODE(LOW_ENERGY_OGF, 0x08),
    CMD_LE_SET_ADVERTISE_ENABLE                 = OPCODE(LOW_ENERGY_OGF, 0x0A),
    CMD_LE_SET_SCAN_PARAMETERS                  = OPCODE(LOW_ENERGY_OGF, 0x0B),
    CMD_LE_SET_SCAN_ENABLE                      = OPCODE(LOW_ENERGY_OGF, 0x0C),
    CMD_LE_CREATE_CONNECTION                    = OPCODE(LOW_ENERGY_OGF, 0x0D),

    CMD_BCM_LOAD_FIRMWARE                = OPCODE(VENDOR_SPECIFIC_OGF, 0x2E),
};

#endif // HCI_CONSTS_H
